[project]
name = "shinytiger"
r_version = "4.6"

repositories = [
    { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest" },
    { alias = "CRAN", url = "https://cran.r-project.org" },
]

dependencies = [
    "shiny",
    "bslib",
    "bsicons",
    "shinyjs",
    "DBI",
    "RSQLite",
    "shinyauthr",
    "sodium",
    "ggplot2",
    "markdown",
    "rclipboard",
    "testthat",
    "withr",
    "pkgload",
]
