# Run from the project root: Rscript deploy/build.R
#
# What this script does:
#   1. Reads all package names from rv.lock
#   2. Queries the Posit Package Manager sysreqs API for Ubuntu 22.04 apt packages
#   3. Writes a fresh Dockerfile into deploy/ using {dockerfiler}
#   4. Documents the R package (regenerates NAMESPACE)
#   5. Builds the shinytigeR tarball into deploy/
#
# After this, run:  docker build --platform linux/amd64 -t shinytiger deploy/

if (!requireNamespace("dockerfiler", quietly = TRUE)) {
  install.packages("dockerfiler", repos = "https://cloud.r-project.org")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite", repos = "https://cloud.r-project.org")
}

pkg_root <- normalizePath(".", mustWork = TRUE)
deploy <- file.path(pkg_root, "deploy")

# ── 1. Read package names from rv.lock ────────────────────────────────────────
lock_path <- file.path(pkg_root, "rv.lock")
lock_text <- readLines(lock_path)
pkgs <- sub(
  '^name = "([^"]+)".*',
  "\\1",
  grep('^name = "', lock_text, value = TRUE)
)
pkgs <- unique(pkgs)
message(sprintf("Found %d packages in rv.lock", length(pkgs)))

# ── 2. Query Posit PPM sysreqs API ────────────────────────────────────────────
ppm_root <- "https://packagemanager.posit.co"
ppm_repo_id <- 1
distro <- "ubuntu"
release <- "22.04"

query_url <- paste0(
  ppm_root,
  "/__api__/repos/",
  ppm_repo_id,
  "/sysreqs?all=false",
  "&distribution=",
  distro,
  "&release=",
  release,
  "&pkgname=",
  paste(pkgs, collapse = "&pkgname=")
)

message("Querying Posit PPM sysreqs API...")
resp <- tryCatch(
  jsonlite::fromJSON(url(query_url), simplifyVector = FALSE),
  error = function(e) {
    warning("Sysreqs API call failed: ", conditionMessage(e))
    list(requirements = list())
  }
)

all_apt <- unique(sort(unlist(lapply(
  resp$requirements,
  function(r) r$requirements$packages
))))
message(
  "System deps: ",
  if (length(all_apt)) paste(all_apt, collapse = ", ") else "(none)"
)

fmt_apt <- function(pkgs) {
  if (length(pkgs) == 0L) {
    return("echo 'No system deps needed'")
  }
  paste0(
    "apt-get update -qq && \\\n",
    "  apt-get install -y --no-install-recommends \\\n",
    paste0("    ", pkgs, collapse = " \\\n"),
    " \\\n  && apt-get clean \\\n  && rm -rf /var/lib/apt/lists/*"
  )
}

# ── 3. Write Dockerfile via dockerfiler ───────────────────────────────────────
# Single-stage: install R packages as pre-compiled binaries from PPM.
# This avoids the rv library-path complexity and is faster (no compilation).
rv_install_cmd <- paste0(
  "RV_VERSION=$(curl -s https://api.github.com/repos/A2-ai/rv/releases/latest",
  " | grep '\"tag_name\"' | sed 's/.*\"v\\([^\"]*\\)\".*/\\1/') && \\\n",
  "  curl -L -o /tmp/rv.tar.gz",
  " \"https://github.com/A2-ai/rv/releases/download/v${RV_VERSION}/",
  "rv-v${RV_VERSION}-x86_64-unknown-linux-gnu.tar.gz\" && \\\n",
  "  tar -xzf /tmp/rv.tar.gz -C /usr/local/bin && \\\n",
  "  chmod +x /usr/local/bin/rv && \\\n",
  "  rm /tmp/rv.tar.gz"
)

df <- dockerfiler::Dockerfile$new(FROM = "rocker/r-ver:4.6")
df$custom("FROM --platform=linux/amd64 rocker/r-ver:4.6", cmd = "")
df$RUN(fmt_apt(c("curl", all_apt)))
df$RUN(rv_install_cmd)
# WORKDIR must be set before rv sync so rv knows the project root
df$WORKDIR("/srv")
df$COPY("rproject.toml", "rproject.toml")
df$COPY("rv.lock", "rv.lock")
# rv sync installs packages; rv activate writes .Rprofile that adds rv's
# library to R's search path — without this, R can't find the packages
df$RUN(paste0(
  "rv sync --locked && \\\n",
  "  RVLIB=$(find /srv/rv/library -mindepth 3 -maxdepth 3 -type d | head -1) && \\\n",
  "  echo \"R_LIBS_USER=$RVLIB\" >> /usr/local/lib/R/etc/Renviron"
))
df$COPY("shinytigeR_*.tar.gz", "/tmp/shinytigeR.tar.gz")
df$RUN(paste0(
  "R CMD INSTALL /tmp/shinytigeR.tar.gz && \\\n",
  "  rm /tmp/shinytigeR.tar.gz && \\\n",
  "  R -e 'library(shinytigeR)'"
))
df$RUN(paste0(
  "addgroup --gid 1003 beitner && \\\n",
  "  adduser --shell /bin/false \\\n",
  "          --uid 1002 --gecos \"Julia Beitner,,,\" \\\n",
  "          --gid 1003 --disabled-password beitner"
))
df$RUN("mkdir -p /opt/shinyapp && chown beitner:beitner /opt/shinyapp")
df$VOLUME('["/opt/shinyapp"]')
df$WORKDIR("/opt/shinyapp")
df$EXPOSE(3838)
df$USER("beitner")
df$ENV("TIGER_DB_DIR", "/opt/shinyapp")
df$custom(
  'CMD ["R", "-e", "options(shiny.port=3838, shiny.host=\'0.0.0.0\'); library(shinytigeR); shinytigeR::run_app()"]',
  cmd = ""
)

header <- "# Generated by deploy/build.R — do not edit by hand.\n# Build with: docker build --platform linux/amd64 -t shinytiger deploy/\n"
dockerfile_path <- file.path(deploy, "Dockerfile")
writeLines(
  paste0(header, "\n", paste(df$Dockerfile[-1], collapse = "\n")),
  dockerfile_path
)
message("Dockerfile written to ", dockerfile_path)

# ── 4. Document + build tarball ───────────────────────────────────────────────
old_tarballs <- list.files(
  deploy,
  pattern = "shinytigeR_.*\\.tar\\.gz",
  full.names = TRUE
)
if (length(old_tarballs)) {
  file.remove(old_tarballs)
  message("Removed: ", paste(basename(old_tarballs), collapse = ", "))
}
message("Documenting and building tarball...")
system2(
  "Rscript",
  c(
    "-e",
    shQuote(paste0(
      "roxygen2::roxygenise('",
      pkg_root,
      "'); ",
      "setwd('",
      pkg_root,
      "'); ",
      "system('R CMD build --no-build-vignettes .')"
    ))
  )
)
tarballs <- list.files(
  pkg_root,
  pattern = "shinytigeR_.*\\.tar\\.gz",
  full.names = TRUE
)
if (length(tarballs) == 0L) {
  stop("R CMD build did not produce a tarball")
}
tarball <- tarballs[order(file.info(tarballs)$mtime, decreasing = TRUE)[1]]
file.rename(tarball, file.path(deploy, basename(tarball)))
message("Built: ", basename(tarball))

message("\n✔ deploy/ is ready. To build the Docker image run:")
message("  docker build --platform linux/amd64 -t shinytiger deploy/")
