FROM rocker/r-ver:4.3.0 AS builder
MAINTAINER Julia Beitner <beitner@psych.uni-frankfurt.de>
RUN apt-get update -qq && \
  apt-get install -y --no-install-recommends \
    git \
    libcurl4-openssl-dev \
    libgit2-dev \
    libicu-dev \
    libsodium-dev \
    libssl-dev \
    make \
    pandoc \
    zlib1g-dev && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/local/lib/R/etc /usr/lib/R/etc/
COPY renv.lock renv.lock
RUN echo "options(renv.config.pak.enabled = FALSE, repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages(c("renv","remotes"))'
RUN R -e 'renv::restore()'
RUN rm renv.lock
